(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const a=function(){console.log("this is about me")},c=function(){console.log("this is benefits")},l=function(){console.log("this is covers")};function u(){console.log("FAQ module loaded successfully!")}document.addEventListener("DOMContentLoaded",()=>{const r=[{question:"What programming languages are most often used in your project?",answer:"In the field of web development, there are various technologies and programming languages. Typically, this includes a combination of frontend (client side) and backend (server side) languages."},{question:"How can I contact you?",answer:"You can contact me via email, phone, or through social media platforms listed on the website."},{question:"What are the deadlines for the project?",answer:"The terms of project implementation depend on a number of factors, such as the scope of the project, its complexity, and the availability of resources. Determining exact deadlines usually occurs during the planning phase."},{question:"Do you provide advice or support?",answer:"Yes! I offer consultations and ongoing support throughout the project lifecycle."},{question:"What payment methods do you accept?",answer:"Payment through credit and debit cards such as Visa, MasterCard, PayPal, as well as payments in cryptocurrencies like Bitcoin and Ethereum."},{question:"What payment methods do you accept?",answer:"Payment through credit and debit cards such as Visa, MasterCard, PayPal, as well as payments in cryptocurrencies like Bitcoin and Ethereum."}],n=document.querySelector(".faq-grid");if(!n){console.error("FAQ container not found!");return}const s=o=>`
      <li class="faq-item">
        <div class="faq-question">
          ${o.question}
          <span class="faq-toggle">
            <!-- Добавлен SVG стрелки -->
            <svg width="12" height="8" viewBox="0 0 12 8" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M11 1.5L6 6.5L1 1.5" stroke="#FAFAFA" stroke-width="2" />
            </svg>
          </span>
        </div>
        <div class="faq-answer hidden">${o.answer}</div>
      </li>
    `;n.innerHTML=r.map(s).join(""),document.querySelectorAll(".faq-item").forEach(o=>{o.addEventListener("click",()=>{o.classList.toggle("active");const e=o.querySelector(".faq-answer");e.classList.toggle("hidden");const t=o.querySelector(".faq-toggle svg");t.style.transform=e.classList.contains("hidden")?"rotate(0deg)":"rotate(180deg)"})})});const d=function(){console.log("this is footer")},f=function(){console.log("this is header")},g=function(){console.log("this is hero")},h=function(){console.log("this is projaect")},m=function(){console.log("this is reviews")};f();g();a();c();h();u();l();m();d();
//# sourceMappingURL=index.js.map
